# Travis CI configuration file for psycopg2

dist: xenial
sudo: required
language: python

services:
    - docker

python:
    - 2.7
    - 3.7
    - 3.6
    - 3.5
    - 3.4

env:
    - IMAGE=piro/manypython_i686   PYDEBUG=
    - IMAGE=piro/manypython_i686   PYDEBUG=d
    - IMAGE=piro/manypython_x86_64 PYDEBUG=
    - IMAGE=piro/manypython_x86_64 PYDEBUG=d

install:
  - sudo scripts/travis_prepare.sh
  - docker pull piro/manypython_i686

script:
  - docker run --rm -v `pwd`:/psycopg2
    -e TEST_PAST -e TEST_FUTURE -e DONT_TEST_PRESENT -e TEST_VERBOSE
    -e PYROOT="/opt/py$(echo $TRAVIS_PYTHON_VERSION | sed 's/\.//')$PYDEBUG"
    $IMAGE /psycopg2/scripts/travis_test.sh

notifications:
  email: false
