# Travis CI configuration file for psycopg2

dist: xenial
sudo: required
language: python

services:
    - docker

matrix:
    include:
        - env:
            PYROOT=py27
        - env:
            PYROOT=py27d
        - env:
            PYROOT=py34
        - env:
            PYROOT=py34d
        - env:
            PYROOT=py35
        - env:
            PYROOT=py35d
        - env:
            PYROOT=py36
        - env:
            PYROOT=py36d
        - env:
            PYROOT=py37
        - env:
            PYROOT=py37d

install:
  - sudo scripts/travis_prepare.sh
  - docker pull piro/manypython_i686


script:
  - docker run --rm -v `pwd`:/psycopg2
    -e TEST_PAST -e TEST_FUTURE -e DONT_TEST_PRESENT -e TEST_VERBOSE
    -e PYROOT=/opt/$PYROOT
    piro/manypython_i686
    /psycopg2/scripts/travis_test.sh

notifications:
  email: false
